# Create an application.yaml file from this template (it is git ignored to protect credentials)

logging:
  level:
    org.springframework:
      web: DEBUG
      security: DEBUG
server:
  error:
    include-stacktrace: never
    include-binding-errors: always
    include-exception: true
    include-message: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/<database>
    username: <username>
    password: <password>
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: <username> # the email to send from, really

    # if using gmail (which should be used for now since the host is defined as smtp.gmail.com),
    # the password used should be a gmail application password - https://support.google.com/accounts/answer/185833?hl=en
    password: <password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

app:
  auth:
    tokenSecret: <token_secret> # must be >=64 preferably random alphanumeric characters (see utils.SecureKeyGenerator)
    tokenExpirationMinutes: 60
  cors:
    allowedOrigins: https://example.com, http://localhost:3000
